# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='aiochsa',
    version='0.1.0',
    description='An experimental wrapper around aiochclient to use it with SQLAlchemy',
    python_requires='==3.*,>=3.7.0',
    license='MIT',
    packages=['aiochsa'],
    package_data={},
    install_requires=[
        'aiochclient==1.*,>=1.2.0', 'clickhouse-sqlalchemy',
        'sqlalchemy==1.*,>=1.3.0'
    ],
    dependency_links=[
        'git+https://github.com/ods/clickhouse-sqlalchemy.git@column_table_prefix#egg=clickhouse-sqlalchemy'
    ],
    extras_require={'dev': ['pylint==2.*,>=2.3.0', 'pytest==5.*,>=5.1.0']},
)
